import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React from "react";

const text = "I have a pen";
const flag = true;

//必須のプロパティを指定する
//？がつくと必須ではなくなる
interface TestComponentProps {
  before: String;
  after?: String;
  //
  children?: React.ReactNode;
}

// コンポーネントを書く
// 自作タグを作成できる！！
// コンポーネントは、大文字から始める！！

//分割代入
//コンポーネントは、ドムは一つだけしか入れては行けない。-> divで囲む
const TestComponent = ({ before, after, children }: TestComponentProps) => {
  return (
    <div>
      <p style={{ fontWeight: "bold", color: "green", fontSize: "48px" }}>
        {before}, は美味しいです。 {after}
      </p>
      {children}
    </div>
  );
};

//データクラスみたいに使う
//divを使いたくないので、<></>で囲む
const TestComponent2 = (props: TestComponentProps) => {
  return (
    <>
      <p style={{ fontWeight: "bold", color: "green", fontSize: "48px" }}>
        {props.before}, おじゃ！ {props.after}
      </p>
      <p>{props.children}</p>
    </>
  );
};


//++++++++++++++++++++++++++++++++++++++++++++++++++++++

interface HeddingProps {
  fontSize: number;
  children?: React.ReactNode;
}

const Heading = (props:HeddingProps) => {
  return (
    <>
      <p
      style={{
        fontWeight: "bold",
        fontSize: `${props.fontSize}px`,
        borderLeft: "solid 8px #0c7abf",
        paddingLeft: "8px",
      }}
    >
        {props.children}
    </p>
    </>
  );
}

//++++++++++++++++++++++++++++++++++++++++++++++++++++++

//コンポーネントの複製
const data = ["HEY", "YO!", "LFG", "WTF"];

//+++++++分割代入の例+++++++++
const { aaa, bbb } = {
  aaa: "aaa",
  bbb: "bbb",
};

const [num1, num2] = [1, 2, 3, 4];

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>


        <h1 className={styles.title}>Hello World</h1>

        {/* 式の代入等はできない */}

        <h2>
          {/*  JSのオブジェクトを代入してくれる */}
          {/* 変数（オブジェクト）・式がかける */}
          {text}
        </h2>

        <h2>
          {/* 三項演算子 論理演算 */}
          {flag ? "true" : "false"}
        </h2>

        <h2>
          {/* 論理演算*/}
          {flag && "true"}
        </h2>

        {/* コンポーネント */}
        {/* プロパティも好きに追加ができる */}
        <TestComponent before="この世界" after="ラーメンも美味しいです" >
          {/* 子要素 */}
          <p>{text}</p>
        </TestComponent>

        <TestComponent2 before="この世界" after="ラーメンも美味しいです" />

        {/* コンポーネントの複製 */}
        {/* いっぱい複写してくれるお */}
        <div>
          {data.map((item) => (
            <TestComponent key={item} before={item} />
          ))}
        </div>

        {/* コールバック */}
        {/* returnに入れられたものを、再代入してくれる */}
        {/* data.map(e => {return (e + 1)}) */}


        {/* ヘッダーを作成する 中央寄せになっているので、100%に設定する */}
        <div style={{width:`100%`}}>
          <Heading fontSize={40}> こんにちは </Heading>
        </div>

  

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
